import type {
  StrategyViewpoint,
  IndustryCandidate,
  StockCandidate,
  AnalysisHypothesis,
  RiskFactor,
  KnowledgeBaseItem,
} from "./analysis-types";

export const mockStrategyViewpoints: StrategyViewpoint[] = [
  {
    id: "vp1",
    title: "科技成长主线延续，AI 算力与半导体为核心",
    direction: "bullish",
    summary: "多家头部券商一致看好科技成长方向，认为 AI 算力需求持续爆发，半导体国产替代加速，是下半年最确定的产业主线。",
    keyPoints: ["AI 大模型训练和推理需求推动算力基础设施投资持续增长", "半导体设备国产化率从 15% 提升至 25%", "消费电子复苏叠加 AI 终端创新"],
    relatedIndustries: ["电子", "计算机", "通信"],
    source: "中信证券、中金公司",
    date: "2026-08-01",
  },
  {
    id: "vp2",
    title: "消费复苏节奏偏慢，结构性机会优于整体",
    direction: "neutral",
    summary: "消费板块整体复苏力度不及预期，但细分领域如食品饮料、家电存在结构性机会，关注龙头企业的份额提升逻辑。",
    keyPoints: ["社零数据增速放缓，消费信心指数仍在低位", "食品饮料龙头 Q2 业绩超预期", "家电以旧换新政策效果显现"],
    relatedIndustries: ["食品饮料", "家用电器", "商贸零售"],
    source: "招商证券、海通证券",
    date: "2026-08-01",
  },
  {
    id: "vp3",
    title: "红利资产仍是底仓配置首选，但需注意拥挤度",
    direction: "neutral",
    summary: "在利率下行环境下，高股息资产仍具配置价值，但部分板块交易拥挤度已偏高，需精选个股而非盲目追高。",
    keyPoints: ["10 年期国债收益率降至 2.1%", "银行、煤炭、交运板块股息率仍具优势", "部分红利 ETF 规模快速增长"],
    relatedIndustries: ["银行", "煤炭", "交通运输"],
    source: "华泰证券、广发证券",
    date: "2026-07-31",
  },
  {
    id: "vp4",
    title: "制造业出海是中长期主线，关注汽车与机械",
    direction: "bullish",
    summary: "中国制造业全球竞争力持续提升，汽车、工程机械、电力设备出海逻辑顺畅，海外收入占比提升带来估值重塑。",
    keyPoints: ["新能源汽车出口量同比增长 45%", "工程机械海外收入占比突破 50%", "电力设备企业受益于全球电网升级"],
    relatedIndustries: ["汽车", "机械设备", "电力设备"],
    source: "中信建投、兴业证券",
    date: "2026-08-01",
  },
];

export const mockIndustryCandidates: IndustryCandidate[] = [
  {
    id: "electronics",
    name: "电子",
    reason: "AI 算力需求爆发驱动半导体产业链高景气，国产替代加速",
    reasons: ["AI 算力需求爆发驱动半导体产业链高景气", "国产替代加速，设备/材料/EDA 全链条突破", "消费电子复苏叠加 AI 手机/PC 创新周期"],
    supportingEvidence: "主力资金连续 2 日净流入 64.84 亿元，12 家机构覆盖，8 家给予买入评级",
    opposingEvidence: "部分细分领域估值已偏高，海外制裁风险仍存",
    pendingEvidence: "Q3 业绩能否持续超预期待验证",
    outlook: "mid_term",
    confidence: "high",
    relatedStocks: ["002371", "688981", "002049"],
    capitalFlow: 64.84,
    institutionCoverage: 12,
    prosperity: "up",
    technicalSignal: "bullish",
  },
  {
    id: "food_beverage",
    name: "食品饮料",
    reason: "龙头业绩超预期，高端化趋势延续，需求改善新周期开启",
    reasons: ["龙头业绩超预期，高端化趋势延续", "主力资金连续 2 日净流入 55.57 亿元", "机构共识度提升，目标价上调"],
    supportingEvidence: "板块涨跌幅 +0.85%，安井食品 3 家机构覆盖，目标价 96.11 元",
    opposingEvidence: "整体消费复苏节奏偏慢，大众品成本压力仍存",
    pendingEvidence: "中秋国庆旺季动销数据待观察",
    outlook: "mid_term",
    confidence: "medium",
    relatedStocks: ["603345"],
    capitalFlow: 55.57,
    institutionCoverage: 8,
    prosperity: "up",
    technicalSignal: "neutral",
  },
  {
    id: "auto",
    name: "汽车",
    reason: "新能源汽车出口高增长，出海逻辑顺畅，智能驾驶技术突破",
    reasons: ["新能源汽车出口高增长，出海逻辑顺畅", "以旧换新政策持续刺激国内需求", "智能驾驶技术突破带来估值提升空间"],
    supportingEvidence: "主力资金连续 2 日净流入 25.07 亿元，新能源汽车出口量同比增长 45%",
    opposingEvidence: "价格战压力仍存，海外贸易壁垒风险",
    pendingEvidence: "Q3 销量数据待验证",
    outlook: "long_term",
    confidence: "high",
    relatedStocks: [],
    capitalFlow: 25.07,
    institutionCoverage: 10,
    prosperity: "up",
    technicalSignal: "bullish",
  },
  {
    id: "computer",
    name: "计算机",
    reason: "AI 应用落地加速，信创需求释放，数据要素政策推动",
    reasons: ["AI 应用落地加速，信创需求释放", "数据要素政策推动行业景气度上行"],
    supportingEvidence: "主力资金今日净流入 23.60 亿元，信创招标量同比增长 60%",
    opposingEvidence: "板块估值处于历史高位，业绩兑现节奏不确定",
    pendingEvidence: "AI 应用商业化落地进度待观察",
    outlook: "mid_term",
    confidence: "medium",
    relatedStocks: [],
    capitalFlow: 23.60,
    institutionCoverage: 9,
    prosperity: "stable",
    technicalSignal: "neutral",
  },
];

export const mockStockCandidates: StockCandidate[] = [
  {
    id: "s1",
    code: "601628",
    name: "中国人寿",
    industry: "保险",
    price: 38.92,
    currentPrice: 38.92,
    changePercent: -3.71,
    marketCap: 11000,
    pe: 7.14,
    pb: 1.84,
    institutionCount: 11,
    rating: "优于大市",
    targetPrice: 48.40,
    upside: 24.36,
    potentialUpside: 24.36,
    reason: "业绩进入兑现阶段，利润增速超预期，投资端收益显著改善，11 家机构覆盖共识度高",
    reasons: ["业绩进入兑现阶段，利润增速超预期", "投资端收益显著改善", "11 家机构覆盖共识度高"],
    risk: "利率下行压缩利差空间，权益市场波动影响投资收益",
    risks: ["利率下行压缩利差空间", "权益市场波动影响投资收益"],
  },
  {
    id: "s2",
    code: "603345",
    name: "安井食品",
    industry: "食品饮料",
    price: 88.90,
    currentPrice: 88.90,
    changePercent: -1.28,
    marketCap: 2600,
    pe: 21.80,
    pb: 1.85,
    institutionCount: 3,
    rating: "买入",
    targetPrice: 96.11,
    upside: 8.11,
    potentialUpside: 8.11,
    reason: "食品饮料需求改善新周期，速冻食品龙头份额持续提升，渠道扩张逻辑顺畅",
    reasons: ["食品饮料需求改善新周期", "速冻食品龙头份额持续提升", "渠道扩张逻辑顺畅"],
    risk: "原材料成本上涨压力，消费复苏不及预期",
    risks: ["原材料成本上涨压力", "消费复苏不及预期"],
  },
  {
    id: "s3",
    code: "002371",
    name: "北方华创",
    industry: "电子",
    price: 285.6,
    currentPrice: 285.6,
    changePercent: 9.98,
    marketCap: 1820,
    pe: 45.2,
    pb: 8.5,
    institutionCount: 15,
    rating: "买入",
    targetPrice: 350.0,
    upside: 22.55,
    potentialUpside: 22.55,
    reason: "半导体设备国产替代核心标的，订单饱满，受益于 AI 算力扩张和国产化率提升",
    reasons: ["半导体设备国产替代核心标的", "订单饱满", "受益于 AI 算力扩张"],
    risk: "估值偏高，海外制裁升级风险，技术迭代不及预期",
    risks: ["估值偏高", "海外制裁升级风险", "技术迭代不及预期"],
  },
];

export const mockHypotheses: AnalysisHypothesis[] = [
  {
    id: "h1",
    type: "industry",
    title: "电子行业进入景气上行阶段",
    description: "AI 算力需求爆发 + 国产替代加速，电子行业景气度持续上行",
    trigger: "AI 大模型训练需求持续增长，半导体设备国产化率突破 25%",
    evidenceChain: ["主力资金连续大幅流入", "机构覆盖数量增加", "龙头业绩超预期"],
    observationMetrics: ["月度半导体设备招标量", "AI 服务器出货量", "板块资金流向"],
    observer: "月度半导体设备招标量、AI 服务器出货量",
    invalidCondition: "AI 资本开支大幅缩减或海外制裁升级导致供应链中断",
    reviewCycle: "每月复盘",
  },
  {
    id: "h2",
    type: "company",
    title: "中国人寿盈利预期上修",
    description: "投资端收益改善 + 保费增长稳健，盈利弹性显现",
    trigger: "1H26 业绩预增，投资收益率显著提升",
    evidenceChain: ["11 家机构覆盖", "目标价上调至 48.40 元", "多头趋势确认"],
    observationMetrics: ["季度净利润增速", "投资收益率", "新业务价值增速"],
    observer: "季度净利润增速、投资收益率",
    invalidCondition: "利率大幅下行导致利差损扩大，或权益市场大幅回调",
    reviewCycle: "每季度复盘",
  },
  {
    id: "h3",
    type: "style",
    title: "市场风格偏向成长",
    description: "利率下行 + 产业趋势明确，成长风格相对价值占优",
    trigger: "10 年期国债收益率降至 2.1%，AI 产业趋势加速",
    evidenceChain: ["成长板块资金持续流入", "成长/价值比值上升", "科技龙头估值扩张"],
    observationMetrics: ["成长/价值指数比值", "科技板块成交额占比", "北向资金流向"],
    observer: "成长/价值指数比值、科技板块成交额占比",
    invalidCondition: "通胀超预期导致利率上行，或成长股业绩大面积不及预期",
    reviewCycle: "每两周复盘",
  },
];

export const mockRisks: RiskFactor[] = [
  {
    id: "r1",
    title: "估值过高",
    category: "valuation",
    description: "部分科技股 PE 处于历史 90% 分位以上，安全边际不足",
    severity: "high",
  },
  {
    id: "r2",
    title: "技术面高位回撤",
    category: "technical",
    description: "电子板块短期涨幅过大，MA20 偏离度偏高，存在回调风险",
    severity: "medium",
  },
  {
    id: "r3",
    title: "机构观点拥挤",
    category: "consensus",
    description: "多家机构同时看好科技成长方向，交易拥挤度偏高",
    severity: "medium",
  },
  {
    id: "r4",
    title: "宏观利率环境不支持",
    category: "macro",
    description: "美联储紧缩预期持续，全球利率高位运行压制成长股估值",
    severity: "high",
  },
];

export const mockKnowledgeBase: KnowledgeBaseItem[] = [
  {
    id: "kb1",
    category: "信息处理",
    title: "自动读取与提取",
    description: "AI 自动读取公告、新闻、研报标题、宏观快照，提取公司、行业、事件、数字、时间、评级变化等关键信息。",
    framework: ["读取原始数据源", "NLP 实体识别", "关键指标提取", "结构化存储"],
    examples: ["从 WSJ 提取：Warsh Tells Congress the Fed Has 'No Tolerance' for High Inflation"],
  },
  {
    id: "kb2",
    category: "证据组织",
    title: "构建证据链",
    description: "将资金流入、研报覆盖提升、技术突破、宏观催化统一到同一个观点下，区分支持/反对/待验证证据。",
    framework: ["收集多维度数据", "归类为支持/反对/待验证", "标注来源和时间戳", "判断短期线索还是中期主线"],
    examples: ["电子板块：资金流入 + 机构覆盖 + 技术突破 = 看多证据链"],
  },
  {
    id: "kb3",
    category: "假设生成",
    title: "形成可追踪假设",
    description: "生成行业/公司/风格/事件假设，每个假设包含触发原因、证据链、观察指标、失效条件和复盘周期。",
    framework: ["识别核心驱动因素", "构建逻辑链条", "设定观察指标", "明确失效条件", "设定复盘周期"],
    examples: ["假设：电子行业进入景气上行阶段。观察指标：月度半导体设备招标量"],
  },
  {
    id: "kb4",
    category: "风险控制",
    title: "多维风险评估",
    description: "不仅输出推荐，也输出风险：估值过高、技术面回撤、机构拥挤、资金流与研报背离、宏观环境不支持等。",
    framework: ["估值水平评估", "技术面位置判断", "交易拥挤度分析", "宏观环境匹配度", "综合风险评级"],
    examples: ["北方华创：PE 45x 处于历史 90% 分位，估值风险高"],
  },
  {
    id: "kb5",
    category: "复盘学习",
    title: "跟踪与反馈",
    description: "跟踪候选标的后续表现，统计信号有效性，识别研报共识与市场背离的情况，根据历史反馈调整打分权重。",
    framework: ["记录候选标的表现", "统计 1/5/20 日收益率", "分析信号组合有效性", "调整模型权重"],
    examples: ["2026-07-15 荐股：燕京啤酒 +3.00%，万华化学 -2.47%"],
  },
];
